### ISSUE TITLE
People (contributors) in annotations not findable

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#102]
A search for all annotations that have a particular contributor in them doesn't work for new contributors who have been added in this recent pass to the biographical list. I don't know if it's restricted to only the contributors who have been added through the annotation editing form, or if it's any new contributor. 

For ex: On this page:
http://library.brown.edu/projects/rome/books/313459/313464/

If  you click on the name "Magni"  you are taken to the people page for Magni, and at the very bottom, you can find his book. If he were associated with only  a few pages, you would see those as well. (see ex. below)

If you click on the other names, Bonfadino, Scultori or Alberti, you go to their people page, but this book or page are not displayed at the bottom. 

That list is the result of a search for all books or annotations that mention that person as a contributor. 
For some reason, searching the annotations for a name doesn't yield results when it's one of the newly added biographies. 

Carlos wrote some of this so he may be able to answer questions as well.

Here's one that works:
http://library.brown.edu/projects/rome/books/256135/256143/

**Comment by bcail** [comment]
OK, I found an error - let me fix that and see if that fixes it completely.

**Comment by bcail** [comment]
Fixed that error, so new annotations will be created with the correct collection id. I'll update the old ones.

**Comment by bcail** [comment]
OK, I updated the old annotations, and the people page for Alberti shows two pages for him now. Please close this issue if it looks good to you.
