### ISSUE TITLE
trying to annotate a print produces server error

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#105]
Not sure why this is happening.
I tried to add an annotation to this print, filled in all the form, but when I clicked submit, it came back with "server error"
https://library.brown.edu/projects/rome/prints/254153/?prints_list_page=1&collection=both

It happened with another print as well. 
https://library.brown.edu/projects/rome/prints/262937/annotations/new/

seems to be consistent. 

This print
https://library.brown.edu/projects/rome/prints/254155/
already had an annotation and I was able to successfully edit it.

**Comment by bcail** [comment]
Sorry, I forgot to enable something on the server. Please try again and close if fixed.
