### ISSUE TITLE
Display "impression" field in annotations

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#108]
Impression date (1582) isn't showing on the annotations--it should be just under the abstract, and would be good if everything in the annotations could display.  An example:
http://library.brown.edu/projects/rome/books/257631/257720/

**Comment by emylonas** [comment]
in the mods, it's this little segment:
<mods:originInfo>
<mods:dateOther type="impression">show me</mods:dateOther>
</mods:originInfo>

**Comment by crotger** [comment]
Fixed by earlier commit
