### ISSUE TITLE
book not displaying all its pages

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#117]
500 server errors when trying to access the second half of  the Buonanno Numismata book
http://library.brown.edu/projects/rome/books/385513/
after image 470 or so.

for ex: http://library.brown.edu/projects/rome/books/385513/386098/
it shows up in the studio view. 
https://repository.library.brown.edu/studio/item/bdr: 386098/

This seems to be the place where it starts:
http://library.brown.edu/projects/rome/books/385513/385982/ shows up
http://library.brown.edu/projects/rome/books/385513/385983/ doesn't show up

**Comment by bcail** [comment]
This might help:
[error]   File "rome_app/views.py", line 167, in page_detail
[error]     if(int(page['rel_has_pagination_ssim']) == (pagenum-1)):
[error] TypeError: int() argument must be a string or a number, not 'list'

**Comment by crotger** [comment]
Just sent a PR for this

On Tue, Feb 17, 2015 at 4:44 PM, bcail <notifications@github.com> wrote:

> This might help:
> [error] File "rome_app/views.py", line 167, in page_detail
> [error] if(int(page['rel_has_pagination_ssim']) == (pagenum-1)):
> [error] TypeError: int() argument must be a string or a number, not 'list'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brown-University-Library/ttwr/issues/117#issuecomment-74760652>
> .
>



-- 
Carlos E. Rotger
Brown University '17
carlos_rotger@brown.edu
Cell: (781) 258-4999
