### ISSUE TITLE
people page isn't working. when you click on a person, it doesn't go to the bio

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#135]
URL it's trying to go to is: 
http://library.brown.edu/projects/rome/people/?book_list_page=

worfdev seems to be working. Is it just that it didn't get moved to production?

**Comment by crotger** [comment]
I think production never was updated, as the code stands right now we shouldn't be getting that book_list_page parameter in the links on the person list page at all.  See commit d0dad28  or PR #129
