### ISSUE TITLE
alphabetizing book titles should be case insensitive

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#139]
book titles alphabetizing is wrong - books with non-sorting article Le, La, etc. appear at the end of the list because they alphabetize on the next word in the title which is often lower case. For ex. 
Le antichità romane sorts after 
Varie vedute

**Comment by lucyvk** [comment]
http://stackoverflow.com/questions/1394475/python-combine-sort-key-functions-itemgetter-and-str-lower

**Comment by lucyvk** [comment]
Pushed to my fork
