### ISSUE TITLE
Test out old image viewer

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#142]
the current open seadragon based image viewer is almost unusable if you zoom and pan a lot, because the mouse "sticks" to the image and you lose the ability to navigate around. This is a known bug. 

According to Joseph, we still have our old image viewer running. Worth testing in case it's easier to use. He says:

" If you want to switch Rome to an older viewer you have https://repository.library.brown.edu/viewers/image/iip/[PID]
EX: https://repository.library.brown.edu/viewers/image/iip/bdr:381111
It's available.  We are not likely to update it. But it is still there."

**Comment by lucyvk** [comment]
The old viewer appears to have less functionality than the current one, the zoom in and out is very jerky and you can visibly see the image reload at each larger or smaller size. You cannot pan on the image using the mouse in the same way that you can with the open seadragon viewer. Switching back to this old viewer would "solve" the sticky mouse problem simply be removing the ability to navigate over the image with panning gestures using the mouse at all, which seems like a loss to me. I think another option MIGHT be to roll back to an earlier version of the OSD viewer, which I can look into tomorrow.

**Comment by lucyvk** [comment]
Change is included in #145

**Comment by lucyvk** [comment]
For now, sticking with old viewer, but some future things to try:
- updating openseadragon viwer
- using openseadragon viewer but blocking all mouse interaction?

**Comment by emylonas** [comment]
The old viewer has met with rousing approval. Evie Linclon and the class really like it. They would like it to be deployed in the 'editing/adding annotation' view as well.

**Comment by lucyvk** [comment]
pushed to my forked copy
