### ISSUE TITLE
Add search for annotation full text - new feature

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#143]
It would be great to be able to search the annotations. 
The fields that make sense are Title, Abstract, and Inscriptions.

**Comment by lucyvk** [comment]
https://repository.library.brown.edu/studio/api-docs/

**Comment by crotger** [comment]
If you don't specify a field in a solr query, it searches a default field for the value you specified. Usually this is set to be a non-stored or aggregate field that includes many parts of the document, but isn't returned as part of search results--it's basically used to make the front-facing search box on the BDR site or other search pages. So typing in "buonanno" to the search page on the bdr [here](https://repository.library.brown.edu/studio/collections/id_621/?q=buonanno), is basically equivalent to the query "ir_collection_id:621 AND buonanno" in the API. 

You could use this to make a pretty complete search page for annotations by making queries like this one: https://repository.library.brown.edu/api/pub/search/?q=ir_collection_id:621+object_type:annotation+display:BDR_PUBLIC+gothorum

**Comment by lucyvk** [comment]
Done with #165
