### ISSUE TITLE
Book metadata for whether or not book is in the Hay

### ISSUE THREAD

**Issue by lucyvk** [Brown-University-Library/ttwr#148]

**Comment by emylonas** [comment]
The books that are part of the Rome digital collection, but not books that are in the Hay have this in their metadata:
```<mods:note>```From the personal collection of Vincent J. Buonanno (Brown '66)```</mods:note>```
I searched for the word Buonanno and it appears in 14 records, haven't checked to see if they are all in a ```<mods:note>``` 
But there seem to be 14 of them.

**Comment by lucyvk** [comment]
Where did you search for the word Buonanno? I want to figure out which books I can use to test this.

**Comment by emylonas** [comment]
In the BDR, looking at the Rome collection:
https://repository.library.brown.edu/studio/collections/id_621/

search inside the collection for Buonnano (note spelling of Buonnano- first
N doubled, second not)

[Elli Mylonas
 Senior Digital Humanities Librarian
 and
 Center for Digital Scholarship
 University Library
 Brown University
 library.brown.edu/cds]

**Comment by lucyvk** [comment]
- Need to figure out if this is indexed in SOLR

**Comment by emylonas** [comment]
There is a _note_ field in the solr results in the bdr. This has the text "From the collection of Vincent J. Buonnano"

**Comment by lucyvk** [comment]
If the note indicates that the book is in the Buonnano private collection, that now displays at the end of the book information on a page detail page.
