### ISSUE TITLE
constraints on people data entry: roles

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#152]
Multiple roles have to be separated by ; (semi colon)
people repeatedly put in ,  (comma)
this results in a role such as "author, editor" which is treated as one string. 

On save, either automatically change comma to semi-colon, or flag as an error and don't save.

**Comment by lucyvk** [comment]
https://docs.djangoproject.com/en/1.9/ref/contrib/admin/

**Comment by lucyvk** [comment]
Doing a string replace of commas for semi-colons for now, pushed to my local fork
