### ISSUE TITLE
Images in TTWR Markdown

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#160]
Is it possible to add images into essay pages in TTWR? More generally, where can I find out what features and what flavor of markdown we are using? 

I tried with this:  ![test image](https://www.flickr.com/photos/29429983@N06/25916123746/) and it didn't work. Ideally the images will be http links, not uploaded to our server. 
tx

**Comment by crotger** [comment]
You can raw HTML into markdown. So 
```html
<img src="https://www.flickr.com/photos/29429983@N06/25916123746/" />
```
renders as:
<img src="https://www.flickr.com/photos/29429983@N06/25916123746/"/>

(though github seems to hate your image link)

**Comment by emylonas** [comment]
hmm, maybe because it doesn't end in jpg...


[Elli Mylonas
 Senior Digital Humanities Librarian
 and
 Center for Digital Scholarship
 University Library
 Brown University
 library.brown.edu/cds]

**Comment by emylonas** [comment]
Just tested with an external image link that ends in jpg and it worked fine. Carlos - I remember (and just tested) that html doesn't work in the TTWR django md...

**Comment by emylonas** [comment]
images work fine as HTML
