### ISSUE TITLE
Prints appear as books on people page

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#161]
Earlier, we used to assume that prints were single file objects and that books were made up of multiple items. It turns out that prints have this information:
<mods:genre authority="aat">etchings (prints)</mods:genre>
So they can be categorized using the mods:genre. 

This was done in order to generate the list of books and list of prints. However, when looking up a person, prints that have images of 2 sides, or have a cropped/uncropped version are showing up under books. They should show up under prints. Ex:
Falda https://library.brown.edu/projects/rome/people/0007/

**Comment by lucyvk** [comment]
Should be good.

One thing I noticed, however is that multi-page prints currently only show one image, like this:

![screenshot 266](https://cloud.githubusercontent.com/assets/6878858/15300419/9b7e1bc4-1b76-11e6-9bcc-3dfab80980e4.png)
The current print interface never shows all of the images in the way that it was doing so mistakenly for the prints it thought were books, like this:
![screenshot 265](https://cloud.githubusercontent.com/assets/6878858/15300425/a1cfabe6-1b76-11e6-8628-2a40f4854fca.png)

**Comment by lucyvk** [comment]
The multi-page prints only showing up as one image is okay for now, so closing
