### ISSUE TITLE
About page isn't editable as admin 

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#162]
The about page is not part of the django admin page that users can access. It would be better if Evie could edit the page. Add about page to admin. Make it work with Markdown

**Comment by lucyvk** [comment]
Currently the about page is just a html file in the project.

- You could maybe add a db table to take care of some of the information (like the contributors)

If there are specific edits that you want made now, you can send them to me and I can put them in the current markdown

**Comment by emylonas** [comment]
Zak - read up on django tables ( @bcail suggestions?) and then make appointment with @bcail to talk through how to do this and other django db fixes. then add table for about page.

**Comment by bcail** [comment]
https://docs.djangoproject.com/en/1.8/topics/migrations/

**Comment by emylonas** [comment]
perhaps make table that can handle more than 1 static page

**Comment by emylonas** [comment]
@zaaakk and @bcail I went to the admin page on worfdev and tried to edit the About page - there is no markdown editor or any way that I can tell to allow me to edit the page. I can see the "statics" choice in the Admin page, and click on that to get to the about page, but that just shows me some runon text - no formatting and no ability to edit. 

No idea about the code block surrounding things in the admin page, best to fix the actual text and not to fix things magically in the code. Can't test if I can't edit.

**Comment by emylonas** [comment]
About page seems to work inside the admin page. 

The formatting doesn't look right however - it was probably formatting as code because of the indentation when it was pasted in. It went away when I removed indentation.

However, we don't handle all the CSS correctly - I've got level 3 headings that don't look right (people list in the about page.) and also paragraphs `<p>` seems to be run on. There is a paragraph break in the middle of the About text, the HTML is there, but no visible paragraph break formatting. The CSS `margin` property seems to be the problem, on `<p>` 

otherwise, fine, let's go with it.

**Comment by bcail** [comment]
ok, so I guess I wait for one more commit for the CSS from @zaaakk?

**Comment by zaaakk** [comment]
hopefully this push fixed it. sorry for the delay on that one.

**Comment by bcail** [comment]
@emylonas deployed to dev server. Let me know if it's ready for production.

**Comment by emylonas** [comment]
looks good

**Comment by bcail** [comment]
PR #250 deployed.
