### ISSUE TITLE
straighten out some roles in annotations

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#171]
need to get back to Ben about this

**Comment by emylonas** [comment]
I am keeping changes here, there will be more to come, no need to act yet...

some changes to annotations that have to be done by Ben:

1. there are 4 annotations that have the role value: "engraver, dedicator"
"bdr:296309", "rel_is_annotation_of_ssim": "bdr:260389"
"bdr:296313", "rel_is_annotation_of_ssim": "bdr:260464"
"bdr:296316", "rel_is_annotation_of_ssim": "bdr:260339"
"bdr:296317", "rel_is_annotation_of_ssim":  "bdr:260541"

These should be changed to just "engraver" as they currently cannot be edited due to the comma. I can add the correct 2nd value once this is done. 

2. Anything that has the attribution "Elli" as the person responsible for a comment should just have that deleted. <note type="resp">Elli</note>

3. <note type="resp">Evie Lincoln</note> should read <note type="resp">E. Lincoln</note>

,

**Comment by emylonas** [comment]
@bcail checking, is this something that was done, and if so can you close?

**Comment by bcail** [comment]
@emylonas I changed these four annotations to be just "engraver". "Dedicator" still needs to be added, if you want it. Closing as you requested.
