### ISSUE TITLE
Book pages not displaying

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#174]
http://library.brown.edu/projects/rome/books/257322/?book_list_page=2
if you click on a page, you get a 500 error. 

the pages show up in the BDR. 

I checked to see if it was maybe a Buonnano book, but it doesn't seem to be. Other book pages are displaying ok.

**Comment by jrhoads** [comment]
From the Logs
 stderr: [ pid=29164, time=2016-07-29 14:41:30,413 ]: Internal Server
Error: /projects/rome/books/257322/257594/
 stderr: Traceback (most recent call last):
 stderr:   File
"/opt/local/django_projects/projects/env/lib/python2.6/site-packages/django/core/handlers/base.py",
line 111, in         get_response
 stderr:     response = callback(request, *callback_args, **callback_kwargs)
 stderr:   File "/opt/local/django_projects/projects/rome_app/views.py",
line 170, in page_detail
 stderr:     if 'Buonanno' in book_json['note'][0]:
 stderr: KeyError: 'note'

It looks like the view is trying to access a field in a dictionary that
does not exist.

**Comment by emylonas** [comment]
ack - this book has no ``note`` elements in its MODS. We just pushed a change that is looking for a value in that field. So it's failing. 
Solution: check for existence of field or remove feature for now. Feature isn't behaving properly but ideally would do so. It's not harming any pages other than the books which have no ``<mods:note>``

**Comment by bcail** [comment]
fixed.
