### ISSUE TITLE
problem saving edited annotations

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#176]
Both Evie and I are having problems submitting changes to annotations. I can log into admin, view an annotation and click the "edit" link, make a change, but on submit I get an Internal Server Error.

**Comment by birkin** [comment]
the code4lib list has a thread about a change to certain services that could result in them not responding if the request isn't formulated in a certain way -- outside chance that could be the issue.

-b
---
mobile email

**Comment by bcail** [comment]
this should be resolved now - please let me know if there's still an issue.
