### ISSUE TITLE
page gives 500 error

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#178]
This page: http://library.brown.edu/projects/rome/books/589836/589963/
doesn't display, instead, gives 500 error. 

This is consistent on all the 2 page spreads in this book. Not sure it happens in other books with 2 page spreads. Apparently, the way these pages were scanned is that there are 3 pages for each foldout - each page is photographed, and then the double page is also photographed. So if there is a 2 page image on page images 126-7, you get 126, 126-7, 127. TTWR isn't behaving well, and I don't know why, unless it's the page name for some reason. 

You can view it in the repository,https://repository.library.brown.edu/studio/item/bdr:589836/
the double pages (see 126-7) display ok as individual pages. They don't do so well in book or portfolio view, but that's to be expected. 

Not sure if this happens in other books. It would be good to understand what is happening in order to see if there are other cases. 

Thank you. --elli

**Comment by bcail** [comment]
views.py, line 211: invalid literal for int(): '126-7'

**Comment by emylonas** [comment]
ok, so it's the page number... would it be ok to change the int to a string? --elli

**Comment by bcail** [comment]
Let me see if I can refactor to not break when the string can be converted to an int.

**Comment by bcail** [comment]
we've merged a fix for this issue, and I deployed it on worfdev. @emylonas, if you could take a look at the basic functionality of the site (especially the previous/next links), we could do a deploy to production tomorrow morning and make sure it fixes this specific 500 error.

**Comment by emylonas** [comment]
@bcail I checked as much as I could - basically, there is only 1 book with pages in it, and it doesn't seem to have any funny numbering. it would be helpful to check the naming if possible, searching for names that have something other than \d in them. [\w\-\.] for ex, to see how frequently this might arise. 

Insofar as I can tell, the behavior is fine, I can go forward and back with no problem in the current examples. Apparently, `next` is handled properly on the last page image, but `previous` is not handled correctly on the first page image of a book. That behavior is pre-existing - no need to deal with it now. (will make new issue for the record)

**Comment by bcail** [comment]
deployed to production - looks fine.
