### ISSUE TITLE
Fix or remove new biography link on create/edit annotation form

### ISSUE THREAD

**Issue by bcail** [Brown-University-Library/ttwr#182]
The link/form for adding new people/Biographies from an annotation form is currently broken. @emylonas - is this link necessary, or are Biographies always created from within the admin anyway?

**Comment by emylonas** [comment]
We've not told anyone that they can add new people from the annotation form, actually. Let's say admin for now.

**Comment by bcail** [comment]
It works now, to add new people/bios from the annotation form. If you want it removed, I can do that, or just leave it.

**Comment by emylonas** [comment]
I worry that people might go and make a biography without checking to see if we already have one. but since it's there and working, I'm going to close
