### ISSUE TITLE
500 error on new site on people Rather Urgent

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#197]
Clicking on a person name in an annotation is a 500 error, Same when clicking on a person on the people page.

**Comment by bcail** [comment]
working on it.

**Comment by bcail** [comment]
fixed and deployed. Let me know if you see any other issues.

**Comment by emylonas** [comment]
[Elli Mylonas
 Senior Digital Humanities Librarian
 and
 Center for Digital Scholarship
 University Library
 Brown University
 library.brown.edu/cds]
