### ISSUE TITLE
500 Error: http://library.brown.edu/projects/rome/books/383007/383068/

### ISSUE THREAD

**Issue by jrhoads** [Brown-University-Library/ttwr#199]
500 Error accessing this URL. http://library.brown.edu/projects/rome/books/383007/383068/
Here's a stacktrace.
Internal Server Error: /projects/rome/books/383007/383068/
Traceback (most recent call last):
  File "../django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../rome_app/views.py", line 206, in page_detail
    context['annotations'] = sorted(context['annotations'], key=lambda annote: annotation_order(annote))
  File "../rome_app/views.py", line 206, in <lambda>
    context['annotations'] = sorted(context['annotations'], key=lambda annote: annotation_order(annote))
  File "../rome_app/views.py", line 26, in annotation_order
    retval = re.sub("[^0-9]", "", first_word(s['orig_title']))
KeyError: 'orig_title'

**Comment by crotger** [comment]
That's frustrating, didn't we just fix a similar error? I'll look at this in about 45 minutes.

**Comment by emylonas** [comment]
do we  need to do a search for this case?

**Comment by crotger** [comment]
pushed a fix to a branch and opened a pr #200

**Comment by bcail** [comment]
fix has been deployed to production.
