### ISSUE TITLE
Deleting annotations

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#211]
1. duplicate annotations on https://repository.library.brown.edu/studio/item/bdr:590488/ there are 3, only 1st (longest) should remain.

**Comment by emylonas** [comment]
Delete top annotation here: http://library.brown.edu/projects/rome/prints/264621/?book_list_page=1

**Comment by bcail** [comment]
fixed 264621.

**Comment by bcail** [comment]
is https://repository.library.brown.edu/studio/item/bdr:590488/ still an issue?

**Comment by emylonas** [comment]
590488 has 3 annotations. The first one (which is the longest, should remain. The other two should be deleted.

**Comment by emylonas** [comment]
need to check which pages have multiple annotations and figure out which are correct (two items on the page, 2 annotations) and which are cases where Evie put in multiples by mistake

**Comment by emylonas** [comment]
fixed. mulitple annotations seems to have been done.
