### ISSUE TITLE
Vincent J. Buonanno not appearing on prints when needed

### ISSUE THREAD

**Issue by zaaakk** [Brown-University-Library/ttwr#213]
Credit for Vincent missing on print page view

**Comment by emylonas** [comment]
also not appearing on single pages of books. cf https://library.brown.edu/projects/rome/books/252532/252571/

**Comment by zaaakk** [comment]
working on this, currently unsure if i need to modify views.py because the issue might be that the notes are not in the django context for the print_list.html page
