### ISSUE TITLE
annotation has problem

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#216]
This annotation won't allow editing - either says "internal server error" or requests password

http://library.brown.edu/projects/rome/login/?next=/projects/rome/books/252240/252360/annotations/295890/edit/

**Comment by bcail** [comment]
@emylonas I think this is the issue:
<name xlink:href="0001" type="personal">
<namePart>Piranesi, Giovanni Battista</namePart>
<role>
<roleTerm type="text"/>
</role>
</name>

There's no role for this name. Is there a role I can add? Or do you want me to remove this name from the annotation completely?

**Comment by emylonas** [comment]
He should be an an "author"

**Comment by emylonas** [comment]
@bcail this is still not working. In order to fix it you have to add the role "author" thank you. Go ahead and close once finished.

**Comment by bcail** [comment]
added "author" and it loads now
