### ISSUE TITLE
prints that are implicit sets

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#244]
viewer should have option that allows 1st child to be displayed, no thumbs in viewer window. 

EM checks all prints that are implicit sets to make sure that we only want 1st child. 

Ben enhances viewer code

Zak calls that code from print view.

**Comment by emylonas** [comment]
implicit set prints
            bdr:590500
            bdr:590503
            bdr:590507
            bdr:590494
            bdr:590497
            bdr:590485
            bdr:590488
            bdr:590491
            bdr:697773
            bdr:381057
            bdr:381090
            bdr:381072
            bdr:381069
            bdr:381075
            bdr:381078
            bdr:381081
            bdr:381063
            bdr:381060
            bdr:381066
            bdr:381084
            bdr:381087

**Comment by emylonas** [comment]
All of these prints need only display the first child object. 

However, bdr:697773 is not a print, it's a book that is full of prints. the MODS needs to be changed.

**Comment by bcail** [comment]
Fixed in #248. Now it only shows the first item of a multi-item print. Maybe, if needed, we could use a new issue to address the bdr:697773 issue?
