### ISSUE TITLE
draughtsman / draftsman in roles

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#270]
In the drop down list of roles when editing the annotation you get both draftsman and draughtsman, and I think we decided on draftsman.  So we need to find the entries for draughtsman and change them to draftsman and get rid of draughtsman.

**Comment by emylonas** [comment]
@bcail this may be easier for you to do than for me. I ran the query that gets me the entries that have "draughtsman" and there appear to be 99, over a few books. Also, I got an error when I tried to edit some of them. 
Could you change "draughtsman" to "draftsman" in annotation roles. This will eliminate the item "draughtsman" from the list of roles that appear in the annotation drop down. Please confirm that this is actually true!

**Comment by bcail** [comment]
@emylonas I just ran a query, and I don't see "draughtsman" in the TTWR collection at all. Could you please let me know how you're running your query, or if it still returns 99 results? Thanks.

**Comment by emylonas** [comment]
I sadly didn't record which query I ran, and it's possible that this was fixed by hand in the interim. However, I just ran this query: 
```
https://repository.library.brown.edu/api/search/?q=ir_collection_id:621+AND+object_type:annotation+AND+display:BDR_PUBLIC&fl=mods_role_ssim,rel_is_annotation_of_ssim,mods_note_resp_ssim&rows=500&start=501
```

and I'm getting 38 of them.  (search for "draughtsman" in the browser.)

**Comment by bcail** [comment]
sorry, my query was bad. There were 101 instances in the TTWR collection, and they should all be fixed now. I deleted "draughtsman" from the DB as well.
