### ISSUE TITLE
New section with inventories

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#274]
On home page make a new item above "links", below "Essays" called "Early Modern Print Shops"

leads to new, editable page on which we will put a list of inventories, some information about them (come from a particular person) and then link to the inventory(ies).

**Comment by zaaakk** [comment]
https://github.com/TEIC/CETEIcean

**Comment by zaaakk** [comment]
The Shops ?

**Comment by emylonas** [comment]
section is there
