### ISSUE TITLE
Notes view related issue?

### ISSUE THREAD

**Issue by zaaakk** [Brown-University-Library/ttwr#276]
http://127.0.0.1:8000/essays/realessay/

**Comment by zaaakk** [comment]
Multiple Notes causes the formatting to break

**Comment by emylonas** [comment]
Hi Zak, can you push this change? production page looks pretty bad. Thank you

**Comment by emylonas** [comment]
I wonder whether we should display Notes differently - for ex, all notes in one orange box, and only show the title and a link to the actual page using the PID.
Also note that the few sentences of essay on the essay boxes show the markdown codes! should't do that

**Comment by zaaakk** [comment]
Recheck if notes are being displayed under notes section

**Comment by zaaakk** [comment]
Maybe write tests to be sure that pids / people are displaying

**Comment by zaaakk** [comment]
Make the author name part of the link

**Comment by zaaakk** [comment]
Make the related content bar work on notes / Notes aren't displaying associated pics in list view

**Comment by zaaakk** [comment]
Instead of "shops" "shop inventories"

**Comment by zaaakk** [comment]
or "Print Shops"

**Comment by emylonas** [comment]
done
