### ISSUE TITLE
Use inherited template structure

### ISSUE THREAD

**Issue by jrhoads** [Brown-University-Library/ttwr#51]
Inherited template structure
  Do not need to pass in the stylesheet.
  Common head and base structure.
  {% extends ‘rome_templates/base.html’ %}

**Comment by crotger** [comment]
The CSS sheets for this project could also use a major refactor. We should try and remove on-element style= attributes and move more styling into separate files. As it is, there's a whole mess of separate sheets, <style> tags, and style= attributes, which can make it hard to tell where a particular change is coming from, and introduces a lot of styles through cascading that can be confusing. 

I'm hoping to start working on both these things in tandem next week.
