### ISSUE TITLE
removing people in annotations

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#92]
I added a person, to test the multiple person behavior. When I tried to remove them, by selecting the dashed lines at the top of the drop down list, i got the message 
"This field is required" and the annotation won't save. 

Also, need to get rid of the 3rd name on this page: (Aquila..., Antiquarian)
"http://library.brown.edu/projects/rome/books/252605/252627/annotations/295688/edit/"

**Comment by bcail** [comment]
Fixed, and the third name has been removed.
