### ISSUE TITLE
some annotations not editable

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#95]
On this page, 
http://library.brown.edu/projects/rome/books/260249/260383/
when you try to edit the annotation, you get a 500 error. This came up when we started trying to fix the annotations that have no genre. There are 115 of them, mostly all of one book. 

Is the error caused by the lack of genre? 

Some are not editable because they have no title. Need help fixing or deleting some of those, as well.

**Comment by bcail** [comment]
This problem is with the roles: "engraver, dedicator" isn't in the database. I think adding "engraver, dedicator" to the role db may fix the issue. Or, adding the same person twice with the two separate roles would probably fix it (might be the best way).

Looks like "dedicator" needs to be added as a role.

I can edit the xml if you let me know what you want it to be.

**Comment by emylonas** [comment]
I've added dedicator and 
Engraver, dedicator
to the list of roles, not seeing a difference. Same internal server error. 
there are others that don't work that have legitimate roles. 
Lauro:
http://library.brown.edu/projects/rome/books/260249/260469/
Barbault:
http://library.brown.edu/projects/rome/books/252605/252704/
Thomas:
http://library.brown.edu/projects/rome/books/253364/253397/
and most of the annotations in this book

is it because the genre is empty?

**Comment by bcail** [comment]
Yes, you fixed the role error - now it's failing because the genre is empty. I'll work on a fix.

**Comment by emylonas** [comment]
ideally, there will no longer be empty roles, so perhaps we should just fix the empties by changing all empty genres to "none" and I'll fix them as soon as we can edit. 

I have all the annotations ids for the empties.

**Comment by bcail** [comment]
I'm able to pull up the edit page on that annotation now. If it works for you, could you please close this issue?

**Comment by emylonas** [comment]
seems to work now, closing issue
