### ISSUE TITLE
change log not working as it should in annotation

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/ttwr#98]
Each annotation has a <note type="resp">xxx</note> element. This is used in lieu of a change log and indicates who has touched the annotation. Currently, when someone edits an annotation that already has the note/@type[resp] note, the value that was in the element before is overwritten with the name of the person who is logged into the django admin and who has just edited the note, erasing the attribution to the original author of the annotation.

The ideal behavior would be to have a real change log that records name, date and role, but MODS doesn't seem to make that easy. 

So - one suggestion for the best way to handle things in the short term would be to
a) if there is a note/@type[resp] with a value, leave it alone

b) if there is nothing, put it in with the current author's credentials from the django admin

c) in the future, make it work properly. 

But we can discuss.

Right now, we've removed information that ascribes assigns authorship to the students who did the original annotations. Can put that back using the mods editor? 

Also, bcail is listed as responsible on some of the annotations!

**Comment by bcail** [comment]
I've updated the code, so there shouldn't be any more annotator information lost. I'll look into the issue of restoring old annotator info.
